version: '3.7'

services:
  developer:
    image: node:lts-alpine
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - ../:/usr/src/code
    working_dir: /usr/src/code
    command: sh -c "npm run img:cp && npm run html:cp && npm run dev"